name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install conventional-changelog-conventionalcommits@4.6.3 semantic-release@19.0.2
          npx semantic-release
