name: Snyk Infrastructure as Code
on: pull_request
jobs:
  snyk:
    runs-on: self-hosted
    steps:
      - name: Snyk Monitor
        uses: eeveebank/github-actions-snyk/monitor@master
        with:
          org_id: ${{ secrets.SNYK_PLATFORM_TERRAFORM_ORG_ID }}
          repository_name: ${{ github.event.repository.name }}
          snyk_token: ${{ secrets.SNYK_PLATFORM_TERRAFORM_TOKEN }}
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Run Snyk Scanning
        uses: eeveebank/github-actions-snyk/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_PLATFORM_TERRAFORM_TOKEN }}
